### ISSUE TITLE
compatible with ESP32

### ISSUE THREAD

**Issue by geofrancis** [pggood/Arduino-AIS-Encode-Si446x#1]
I have tried to make this for a esp32 but i get the errors:

`Si446x_AIS_decode:74:15: error: 'unsigned char sync' redeclared as different kind of symbol
 unsigned char sync;        
               ^~~~       

c:\users\geo\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\sys-include\sys\unistd.h:309:9: note: previous declaration 'void sync()'         
 void    sync (void);          
         ^~~~       

D:\Documents\CODE\Arduino Sketches\Arduino_AIS-master\Si446x_AIS_decode\Si446x_AIS_decode.ino: In function 'void configure()':          
Si446x_AIS_decode:117:17: error: unused variable 'configvalue' [-Werror=unused-variable]
   unsigned char configvalue;       
                 ^~~~~~~~~~~

D:\Documents\CODE\Arduino Sketches\Arduino_AIS-master\Si446x_AIS_decode\Si446x_AIS_decode.ino: In function 'void loop()':
Si446x_AIS_decode:610:8: error: unused variable 'radio_channel' [-Werror=unused-variable]        
   char radio_channel;    
        ^~~~~~~~~~~~~

Si446x_AIS_decode:611:17: error: unused variable 'curr_fragment' [-Werror=unused-variable]
   unsigned char curr_fragment = 1;
                 ^~~~~~~~~~~~~

Si446x_AIS_decode:612:17: error: unused variable 'total_fragments' [-Werror=unused-variable]
   unsigned char total_fragments = 1;
                 ^~~~~~~~~~~~~~~

Si446x_AIS_decode:613:16: error: unused variable 'packet_bits' [-Werror=unused-variable]
   unsigned int packet_bits;
                ^~~~~~~~~~~

Si446x_AIS_decode:614:16: error: unused variable 'packet_pos' [-Werror=unused-variable]
   unsigned int packet_pos;
                ^~~~~~~~~~

Si446x_AIS_decode:615:17: error: unused variable 'nmea_message_id' [-Werror=unused-variable]
   unsigned char nmea_message_id = 0;
                 ^~~~~~~~~~~~~~~

Si446x_AIS_decode:616:17: error: unused variable 'raw_byte' [-Werror=unused-variable]
   unsigned char raw_byte;
                 ^~~~~~~~

Si446x_AIS_decode:617:17: error: unused variable 'raw_bit' [-Werror=unused-variable]
   unsigned char raw_bit;
                 ^~~~~~~

Si446x_AIS_decode:618:17: error: unused variable 'nmea_byte' [-Werror=unused-variable]
   unsigned char nmea_byte=0;
                 ^~~~~~~~~

Si446x_AIS_decode:619:17: error: unused variable 'nmea_bit' [-Werror=unused-variable]
   unsigned char nmea_bit=6;
                 ^~~~~~~~

Si446x_AIS_decode:620:17: error: unused variable 'stuff_bits' [-Werror=unused-variable]
   unsigned char stuff_bits;
                 ^~~~~~~~~~

cc1plus.exe: some warnings being treated as errors

Multiple libraries were found for "SPI.h"

 Used: C:\Users\Geo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\SPI
 Not used: D:\Documents\Arduino\libraries\SPI
Using library SPI at version 2.0.0 in folder: C:\Users\Geo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\SPI 
exit status 1
'unsigned char sync' redeclared as different kind of symbol

`

**Comment by pggood** [comment]
Whats your development environment?  It compiles error free using the ESP32 plugin from Espressif System from the board manager can you turn on verbose compiler logging and upload the compile log

**Comment by geofrancis** [comment]
Thank you for your reply. will try again and get back to you, I think i was using the arduino esp32 library and not the expressif version.

**Comment by geofrancis** [comment]
are there any libraries that are required for it?

**Comment by geofrancis** [comment]
I tried with the expressif library but I still get errors, it compiles for the arduino nano and the rp2040 ok . what version of the library are you using and did you make any modifications to the code to get it to work?

what module are you compiling it for?

D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\si446x_patch.h:16:45: warning: backslash-newline at end of file
   16 | #define SI446X_PATCH_CMDS                   \
      |                                              
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\gpslookup.cpp: In member function 'bool Gpslookup::gpsdata(char)':
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\gpslookup.cpp:13:12: warning: comparison is always true due to limited range of data type [-Wtype-limits]
   13 |   if (data != -1){
      |       ~~~~~^~~~~
gpslookup.cpp:27:53: error: array subscript has type 'char' [-Werror=char-subscripts]
   27 |                                         if(rxBuffer[i]!=starting[i])bufferEnabled=0;
      |                                                     ^
gpslookup.cpp:27:66: error: array subscript has type 'char' [-Werror=char-subscripts]
   27 |                                         if(rxBuffer[i]!=starting[i])bufferEnabled=0;
      |                                                                  ^
gpslookup.cpp:43:56: error: array subscript has type 'char' [-Werror=char-subscripts]
   43 |                                 for (i=0; i<8; i++)lat[i]=rxBuffer[i];
      |                                                        ^
gpslookup.cpp:43:68: error: array subscript has type 'char' [-Werror=char-subscripts]
   43 |                                 for (i=0; i<8; i++)lat[i]=rxBuffer[i];
      |                                                                    ^
gpslookup.cpp:52:56: error: array subscript has type 'char' [-Werror=char-subscripts]
   52 |                                 for (i=0; i<9; i++)lon[i]=rxBuffer[i];
      |                                                        ^
gpslookup.cpp:52:68: error: array subscript has type 'char' [-Werror=char-subscripts]
   52 |                                 for (i=0; i<9; i++)lon[i]=rxBuffer[i];
      |                                                                    ^
gpslookup.cpp:72:42: error: array subscript has type 'char' [-Werror=char-subscripts]
   72 |                                 rxBuffer[i]=0;
      |                                          ^
gpslookup.cpp:77:46: error: array subscript has type 'char' [-Werror=char-subscripts]
   77 |                         rxBuffer[rxWriteIndex++] = data;
      |                                  ~~~~~~~~~~~~^~
gpslookup.cpp:101:74: error: array subscript has type 'char' [-Werror=char-subscripts]
  101 |                                                                 rxBuffer[i]=0;
      |                                                                          ^
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\si446x.cpp: In member function 'void si446x::setFrequency(uint32_t, uint16_t)':
si446x.cpp:364:72: error: narrowing conversion of '(band + sy_sel)' from 'uint32_t' {aka 'long unsigned int'} to 'uint8_t' {aka 'unsigned char'} [-Werror=narrowing]
  364 |   uint8_t set_band_property_command[] = {0x11, 0x20, 0x01, 0x51, (band + sy_sel)};
      |                                                                  ~~~~~~^~~~~~~~~
si446x.cpp:382:71: error: narrowing conversion of 'n' from 'uint32_t' {aka 'long unsigned int'} to 'uint8_t' {aka 'unsigned char'} [-Werror=narrowing]
  382 |   uint8_t set_frequency_property_command[] = {0x11, 0x40, 0x04, 0x00, n, m2, m1, m0, c1, c0};
      |                                                                       ^
si446x.cpp:382:74: error: narrowing conversion of 'm2' from 'uint32_t' {aka 'long unsigned int'} to 'uint8_t' {aka 'unsigned char'} [-Werror=narrowing]
  382 |   uint8_t set_frequency_property_command[] = {0x11, 0x40, 0x04, 0x00, n, m2, m1, m0, c1, c0};
      |                                                                          ^~
si446x.cpp:382:78: error: narrowing conversion of 'm1' from 'uint32_t' {aka 'long unsigned int'} to 'uint8_t' {aka 'unsigned char'} [-Werror=narrowing]
  382 |   uint8_t set_frequency_property_command[] = {0x11, 0x40, 0x04, 0x00, n, m2, m1, m0, c1, c0};
      |                                                                              ^~
si446x.cpp:382:82: error: narrowing conversion of 'm0' from 'uint32_t' {aka 'long unsigned int'} to 'uint8_t' {aka 'unsigned char'} [-Werror=narrowing]
  382 |   uint8_t set_frequency_property_command[] = {0x11, 0x40, 0x04, 0x00, n, m2, m1, m0, c1, c0};
      |                                                                                  ^~
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\Si446x_AIS_encode.ino: In function 'void si4464_9600()':
Si446x_AIS_encode:52:20: error: unused variable 'tcnt' [-Werror=unused-variable]
   52 |     static uint8_t tcnt = 0;
      |                    ^~~~
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\si446x.cpp: In member function 'void si446x::startTx(uint16_t)':
si446x.cpp:438:67: error: narrowing conversion of '(int)(((short unsigned int)((int)(size >> 8))) & 31)' from 'int' to 'uint8_t' {aka 'unsigned char'} [-Werror=narrowing]
  438 |   uint8_t change_state_command[] = {0x31, 0x00, 0x30, (size >> 8) & 0x1F, size & 0xFF};
      |                                                       ~~~~~~~~~~~~^~~~~~
si446x.cpp:438:80: error: narrowing conversion of '(int)(((short unsigned int)((int)size)) & 255)' from 'int' to 'uint8_t' {aka 'unsigned char'} [-Werror=narrowing]
  438 |   uint8_t change_state_command[] = {0x31, 0x00, 0x30, (size >> 8) & 0x1F, size & 0xFF};
      |                                                                           ~~~~~^~~~~~
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\Si446x_AIS_encode.ino: In function 'void loop()':
Si446x_AIS_encode:130:8: error: unused variable 'incomingByte' [-Werror=unused-variable]
  130 |   char incomingByte;
      |        ^~~~~~~~~~~~
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\ais.cpp: In member function 'void Ais::finalize(uint8_t*, uint16_t&)':
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\ais.cpp:161:39: warning: compound assignment with 'volatile'-qualified left operand is deprecated [-Wvolatile]
  161 |         if (payload[i]) Packet[index] |= ( 1 << offset );
      |                         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\ais.cpp: In member function 'void Ais::nrziEncode(uint8_t*, uint16_t&)':
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\ais.cpp:229:36: warning: compound assignment with 'volatile'-qualified left operand is deprecated [-Wvolatile]
  229 |         if ( NRZI) TXPacket[index] |= ( 1 << offset );
      |                    ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\ais.cpp:234:23: warning: compound assignment with 'volatile'-qualified left operand is deprecated [-Wvolatile]
  234 |       TXPacket[index] |= ( 0 << offset );
      |       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\Si446x_AIS_encode.ino: At global scope:
Si446x_AIS_encode:52:20: error: 'tcnt' defined but not used [-Werror=unused-variable]
   52 |     static uint8_t tcnt = 0;
      |                    ^~~~
cc1plus.exe: some warnings being treated as errors
cc1plus.exe: some warnings being treated as errors
ais.cpp:234:21: error: 'index' may be used uninitialized [-Werror=maybe-uninitialized]
  234 |       TXPacket[index] |= ( 0 << offset );
      |       ~~~~~~~~~~~~~~^
D:\Documents\CODE\Arduino Sketches\Arduino-AIS-Encode-Si446x-master\Si446x_AIS_encode\ais.cpp:221:14: note: 'index' was declared here
  221 |     uint16_t index ;
      |              ^~~~~
cc1plus.exe: some warnings being treated as errors
cc1plus.exe: some warnings being treated as errors
Multiple libraries were found for "SPI.h"
 Used: C:\Users\Geo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha3\libraries\SPI
 Not used: D:\Documents\Arduino\libraries\SPI
Using library SPI at version 2.0.0 in folder: C:\Users\Geo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha3\libraries\SPI 
exit status 1
array subscript has type 'char' [-Werror=char-subscripts]


what esp32 module did you compile it for?

**Comment by geofrancis** [comment]
I updated from arduino 1.8 to 2.2 and it now compiles, my plan is to use the second core on the esp32 to run the ais system leaving core 1 free.

**Comment by MJYaire** [comment]
hello, how you work going? Your work is close to mine. Running the ais system the second core on the esp32 is for low power？
